// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdgGZ3N0D2-o2FnSPIj4Rr0jCV19sjWcE',
    appId: '1:515040773913:web:121ee8aafe75fbce74e788',
    messagingSenderId: '515040773913',
    projectId: 'taskmate-c40db',
    authDomain: 'taskmate-c40db.firebaseapp.com',
    storageBucket: 'taskmate-c40db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2uni_lcvLC-oZQ_mzTnN5wLVSJH4d-EE',
    appId: '1:515040773913:android:f12bef4487c83d6674e788',
    messagingSenderId: '515040773913',
    projectId: 'taskmate-c40db',
    storageBucket: 'taskmate-c40db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYwquTExyU-vydHfiUEEMj0Q-EPn86v_M',
    appId: '1:515040773913:ios:4cf3381849e061fb74e788',
    messagingSenderId: '515040773913',
    projectId: 'taskmate-c40db',
    storageBucket: 'taskmate-c40db.firebasestorage.app',
    iosBundleId: 'com.example.taskmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYwquTExyU-vydHfiUEEMj0Q-EPn86v_M',
    appId: '1:515040773913:ios:4cf3381849e061fb74e788',
    messagingSenderId: '515040773913',
    projectId: 'taskmate-c40db',
    storageBucket: 'taskmate-c40db.firebasestorage.app',
    iosBundleId: 'com.example.taskmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdgGZ3N0D2-o2FnSPIj4Rr0jCV19sjWcE',
    appId: '1:515040773913:web:295373c0f6b45e2474e788',
    messagingSenderId: '515040773913',
    projectId: 'taskmate-c40db',
    authDomain: 'taskmate-c40db.firebaseapp.com',
    storageBucket: 'taskmate-c40db.firebasestorage.app',
  );
}
